### ISSUE TITLE
v0.1.7 on pypi

### ISSUE THREAD

**Issue by glehmann** [click-contrib/click-spinner#18]
Sorry to bother you with that, but could you publish the last version on pypi?

**Comment by yoavram** [comment]
I believe it is already there: https://pypi.python.org/pypi/click-spinner/
Travis takes care of that...
Let me know if you still can't install.

**Comment by glehmann** [comment]
Indeed it is. Something went wrong when I tried to update it earlier, but now it's working.
I'm even more sorry to have bothered you with that!

**Comment by yoavram** [comment]
No worries
