### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by ltalirz** [click-contrib/click-spinner#22]
Dear @yoavram , I am in the process of adding a recipe for click-spinner to [conda-forge](https://conda-forge.org/)
https://github.com/conda-forge/staged-recipes/pull/5952

In this process, I've encountered a few minor issues that I would kindly ask you to address:
- [ ] consider including the tests in your pypi release by adding something like `recursive-include tests *.py` to your `MANIFEST.in`. This would allow using the pypi release for automatic tests on conda-forge
- [ ] minor: when running `nosetests` inside the `tests` directory, one of the tests fails (tests run fine, when running `nosetests` in top-level directory)
- [ ] please add a license of your choice to your repository
- [ ] please let me know if you would like to be listed as a maintainer of the conda recipe or not

**Comment by yoavram** [comment]
Hi @ltalirz sorry for such a late reply. If you want to create a PR with the required changes feel free and I’ll try to merge it asap. License can be any permissive open source like BSD or MIT I guess. No need for me to be a maintainer.
