### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by thehappydinoa** [click-contrib/click-spinner#24]
This error repeats itself over and over again in the console.
```
objc[73294]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by yoavram** [comment]
Looks like an objective-c error, not python... what are you running?

**Comment by thehappydinoa** [comment]
I literally just added your spinner, and it started, everything was working before.

**Comment by yoavram** [comment]
Yes, I understand, I'm asking what you are running, because the error you cite is and Objective-C error, not a Python error. Are you calling python from Objective-C? Are you calling Objective-C from Python?

**Comment by thehappydinoa** [comment]
Ah I'm sorry, it was just a simple website scraper, it's pure python 3.6. I
import `requests` and it works fine so I have no idea. Maybe it's something
with threading?
